name: Deploy on Push (lint-not-blocking)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: self-hosted
    continue-on-error: true   # never blocks your work if this fails
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ping local backend (optional)
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          try {
            $r = Invoke-WebRequest -Uri "http://localhost:8000/health" -TimeoutSec 5 -UseBasicParsing
            Write-Host "Health: $($r.StatusCode)"
          } catch {
            Write-Host "Backend not reachable (that’s OK on CI): $($_.Exception.Message)"
          }
