name: Deploy on Push (lint-not-blocking)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruff (non-blocking)
        shell: powershell
        continue-on-error: true
        run: |
          python --version 2>$null
          if ($LASTEXITCODE -ne 0) { choco install -y python --version=3.11.9 }
          python -m pip install --upgrade pip
          python -m pip install ruff==0.13.0
          ruff check .

      - name: Deploy with Docker Compose
        shell: powershell
        env:
          COMPOSE_HTTP_TIMEOUT: 200
        run: |
          docker --version
          docker compose version
          docker compose up -d --build

          $api = "http://localhost:8000/health"
          $deadline = (Get-Date).AddMinutes(3); $ok=$false
          while((Get-Date) -lt $deadline){
            try {
              $resp = Invoke-WebRequest -Uri $api -TimeoutSec 6
              if ($resp.StatusCode -eq 200 -and ($resp.Content -like "*ok*")) { $ok=$true; break }
            } catch {}
            Start-Sleep 3
          }
          if (-not $ok) {
            Write-Host "Recent backend logs:"; docker compose logs --tail 200 backend
            throw "Backend /health did not become OK."
          }
          Write-Host "✅ Deploy finished; health OK."
