name: Deploy on Push (lint-not-blocking)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      # 1) Check out the repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Optional: run Ruff but DO NOT fail the job
      - name: Install Python + Ruff (for info only)
        shell: powershell
        continue-on-error: true
        run: |
          python --version 2>$null
          if ($LASTEXITCODE -ne 0) { choco install -y python --version=3.11.9 }
          python -m pip install --upgrade pip
          python -m pip install ruff==0.13.0

      - name: Ruff lint (non-blocking)
        shell: powershell
        continue-on-error: true
        run: |
          ruff --version
          ruff check .

      # 3) Deploy on this machine (the Windows self-hosted runner)
      - name: Deploy with Docker Compose
        shell: powershell
        working-directory: ${{ github.workspace }}
        env:
          COMPOSE_HTTP_TIMEOUT: 200
        run: |
          Write-Host "Ensuring PowerShell can run scripts in this session..."
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

          Write-Host "Docker version:"; docker --version
